### ISSUE TITLE
Don’t include ZIP files into the git repo.

### ISSUE THREAD

**Issue by ypid** [GORywwyN/ksp-thesis#1]
Hi

I just noticed that you seem to put zip files of all releases into the git repo: https://github.com/GORywwyN/ksp-thesis/tree/master/release

I would suggest against doing this as this will blow up the repo size. When you probably tag (git tag) your releases GitHub will provide archives of that version. When you include builds which are otherwise not tracked you can upload your own binaries to those releases.

**Comment by GORywwyN** [comment]
Thanks for pointing this out. You are indeed correct that it will be better to track previous releases with _git tag_. I have changed my release-folder to contain only the current relase. (I still want to serve users the most current zip-file, as it contains the files in a installation-friendly folder structure.)

**Comment by ypid** [comment]
> I still want to serve users the most current zip-file, as it contains the files in a installation-friendly folder structure.

Sure, that should be doable by uploading it on the release page of GitHub as mentioned.
